# Generated by Django 5.0.7 on 2025-04-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOI_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('external_link', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='IMBD_News',
        ),
    ]
